version: "3"
services:
  web:
    build: ./
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=8080
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./main.py
    ports: ['8080:8080']
    volumes: ['./:/app']
